Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license()" for more information.
>>> thon/OOP_test_1.py
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    thon/OOP_test_1.py
NameError: name 'thon' is not defined
>>> 
=============== RESTART: /home/user/EDIBO/Python/OOP_test_1.py ===============
Before an = PartyAnimal()
After an = PartyAnimal()

Before first an.party()
So far 1
After first an.party()

Before second an.party()
So far 2
After second an.party

Before third an.party()
So far 3
After third an.party()

Before one more party()
So far 4
After one more party()
>>> 
=============== RESTART: /home/user/EDIBO/Python/OOP_test_1.py ===============
Before an = PartyAnimal()
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/user/EDIBO/Python/OOP_test_1.py', 'PartyAnimal': <class '__main__.PartyAnimal'>}
After an = PartyAnimal()
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/user/EDIBO/Python/OOP_test_1.py', 'PartyAnimal': <class '__main__.PartyAnimal'>, 'an': <__main__.PartyAnimal object at 0x7f6201dda3c8>}

Before first an.party()
So far 1
After first an.party()

Before second an.party()
So far 2
After second an.party

Before third an.party()
So far 3
After third an.party()

Before one more party()
So far 4
After one more party()
>>> 
